apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: little-diare-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
    - host: {{.Values.services.webService}}
      http:
        paths:
          - path: /
            backend:
              serviceName: web-service
              servicePort: 3000
    - host: {{.Values.services.authService}}
      http:
        paths:
          - path: /
            backend:
              serviceName: auth-service
              servicePort: 5000
    - host: {{.Values.services.familyService}}
      http:
        paths:
          - path: /
            backend:
              serviceName: family-service
              servicePort: 5000
    - host: {{.Values.services.measurementService}}
      http:
        paths:
          - path: /
            backend:
              serviceName: measurement-service
              servicePort: 8080