apiVersion: v1
kind: Secret
metadata:
  name: measurement-auth-secrets
type: Opaque
stringData:
  MEASUREMENT_SERVICE_AUTH_SERVER_USERNAME: {{ .Values.integrations.authServiceUsername }}
  MEASUREMENT_SERVICE_AUTH_SERVER_PASSWRD: "{{ .Values.integrations.authServicePassword}}"