name: Deploy measurement service
on:
  repository_dispatch:
    types: [measurement-service-released]

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1

    - name: 'Deploy'
      uses: 'deliverybot/helm@v1'
      with:
        helm: 'helm3'
        release: 'measurement-chart'
        namespace: 'ld-dev'
        chart: 'k8s/measurement_service'
        token: '${{ github.token }}'
        values: |
          postgresql:
            postgresqlPassword: "${{ secrets.MEASUREMENT_DB_PASSWORD }}"
          properties:
            jwtPublicKey: "${{ secrets.JWT_PUBLIC_KEY }}"
          image:
            tag: "${{ github.event.client_payload.version }}"
          integrations:
            authServicePassword: "${{ secrets.MEASUREMENT_USER_PASSWORD }}"
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
