name: Deploy web app
on:
  push:
  repository_dispatch:
    types: [web-app-released]

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
    - uses: actions/checkout@v1

    - name: 'Deploy'
      uses: 'deliverybot/helm@v1'
      with:
        helm: 'helm3'
        release: 'web-chart'
        namespace: 'ld-dev'
        chart: 'k8s/web_app'
        token: '${{ github.token }}'
        values: |
          integrations:
            authServerUrl: "https://auth.ld.de1mos.net"
            familyServerUrl: "https://family.ld.de1mos.net"
          image:
            tag: "${{ github.event.client_payload.version }}"
      env:
        KUBECONFIG_FILE: '${{ secrets.KUBECONFIG }}'
