postgresql:
  postgresqlPassword: "${{ secrets.AUTH_DB_PASSWORD }}"
  resources:
    requests:
      cpu: 0.1
  properties:
    jwtPrivateKey: "${{ secrets.JWT_PRIVATE_KEY }}"
    jwtPublicKey: "${{ secrets.JWT_PUBLIC_KEY }}"
  image:
    tag: "${{ github.event.client_payload.version }}"